### PR TITLE
Add enabled flag so consumers can enable/disable haptics

### PR DESCRIPTION
**Pull request by bengilroy**
Recently on a project we had a crash due to some haptic events accidentally being called on the background thread, we decided to temporarily disable all haptics entirely for the release by editing the HapticGenerator pod instead of un-integrating it across the codebase.

I think it would be useful to provide this feature as part of HapticGenerator, some consumers may even wish to provide this option in an app's settings.

### CODE REVIEW

**Comment by KaneCheshire** [comment]
Hmm not sure how I feel about this one. Feels like a bandage over an issue where HapticGenerator could do more to either flag up when its being run on a non-main thread, or maybe even force that haptic generation happens on the main thread?

I'd rather not add something for such an edge case, especially since haptics can already be turned off system-wide by users so it's not even really a valid case to say it could be user configurable.

**Comment by bengilroy** [comment]
@KaneCheshire That's fair enough, this wasn't intended as a bandage or as a solution to the edge case or crash, but felt it might be useful for some consumers to be able to disable all haptics in the app without having to remove implementation just so it's more flexible (for whatever reason).

I guess they can be turned off system wide, but I've seen apps offer the ability to turn off haptic feedback in app settings rather than system wide (most notably Calzy which is an Apple Design Award winner). In the current implementation of HapticGenerator, I'd have to add some sort of wrapper around HapticGenerator in order to achieve this (although maybe you might want consumers to do this, I'm not sure) or perhaps just use the `HapticGenerator.swift` file directly and edit it yourself.

Let me know what you think, happy to close this PR if you feel it's a step in the wrong direction. I'll create an issue for the main thread discussion as I feel like that's separate 🙂

**Comment by KaneCheshire** [comment]
I think you could get away with just an extension on `Haptic` that checks a user preference before generating any haptics, which I would expect to be the responsibility of the consumer personally. I do understand where the motivation comes from, but don't know if it should sit in the pod?

Another thing that slightly irks me is that the way static properties previously read is quite nice:

`Haptic.success.generate()`

And adding a different static property on Haptic now mixes that with `Haptic.isEnabled`, and it's not super clear that it's disabling it for all haptics when you put them side by side. 

Let me mull over it for a bit!

**Comment by bengilroy** [comment]
I agree with the naming bit for sure, we haven't updated to the latest version yet, so it made more sense before e.g. `HapticGenerator.isEnabled` makes more sense as you're disabling a generator, rather than disabling a `Haptic`. Open to alternative of how this could be implemented also, I'll let you have a think 🙂

**Pull request closed without merging**
